### ISSUE TITLE
add a logo to the github org

### ISSUE THREAD

**Issue by gbinal** [GSA/GitHub-Administration#26]
I think there used to be one but the logo appears to be missing now from this org.  Could an admin add one?

https://www.gsa.gov/reference/gsa-logo-policy/download-gsa-logo

**Comment by adunkman** [comment]
Seems to be fixed now.

**Comment by mjtanski** [comment]
I just replaces the logo with the GSA logo

**Comment by konklone** [comment]
I don't mean to nitpick, but it's a little blurry on my Mac screen:

<img width="502" alt="screen shot 2018-11-27 at 11 31 56 am" src="https://user-images.githubusercontent.com/4592/49096204-176e6000-f238-11e8-92f7-ac14287d9d1a.png">

Here's a higher-res one, adapted from the official Insite page:

![gsa_star_mark_ rgb](https://user-images.githubusercontent.com/4592/49096510-b72bee00-f238-11e8-8d0d-cfb316cc880a.png)

Could this be used in place of the current one?

**Comment by konklone** [comment]
It looks great now! Thank you.

<img width="510" alt="screen shot 2018-11-27 at 12 58 49 pm" src="https://user-images.githubusercontent.com/4592/49101439-3672ef00-f244-11e8-9dbf-c6f25bd9652f.png">
